In [3]:
import pandas as pd

In [4]:
df=pd.read_csv('yahoo_finance.csv')

In [5]:
df

,ticker,asset_class,shortName,longName,symbol,exchange,quoteType,currency,country,sector,...,market_cap_usd,sector_return_rank,sector_momentum_rank,asset_class_return_rank,asset_class_momentum_rank,fear_greed_proxy,fear_greed_label,week52_position_pct,week52_zone,composite_score
0,000660.KS,INTL,SK hynix,SK hynix Inc.,000660.KS,KSC,EQUITY,KRW,South Korea,Technology,...,4.531433e+11,2.0,3.0,1,1,48.0,NEUTRAL,76.2,NEAR_HIGH,37.3
1,005930.KS,INTL,SamsungElec,"Samsung Electronics Co., Ltd.",005930.KS,KSC,EQUITY,KRW,South Korea,Technology,...,9.563575e+11,5.0,4.0,2,2,55.3,NEUTRAL,78.4,NEAR_HIGH,38.1
2,035420.KS,INTL,NAVER,NAVER Corporation,035420.KS,KSC,EQUITY,KRW,South Korea,Communication Services,...,2.179156e+10,9.0,4.0,52,51,56.2,NEUTRAL,17.9,NEAR_LOW,27.7
3,AAPL,US_MEGA,Apple Inc.,Apple Inc.,AAPL,NMS,EQUITY,USD,United States,Technology,...,3.819844e+12,24.0,22.0,32,54,75.6,GREED,72.6,UPPER_HALF,32.7
4,AAVE-USD,CRYPTO,Aave USD,Aave USD,AAVE-USD,CCC,CRYPTOCURRENCY,USD,NaN,NaN,...,1.489162e+09,NaN,NaN,11,36,41.7,NEUTRAL,1.1,NEAR_LOW,20.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
446,^TA125.TA,INDICES,TA-125,TA-125,^TA125.TA,TLV,INDEX,ILS,NaN,NaN,...,NaN,NaN,NaN,4,5,72.7,GREED,88.4,NEAR_HIGH,33.0
447,^TNX,INDICES,CBOE Interest Rate 10 Year T No,CBOE Interest Rate 10 Year T No,^TNX,CGI,INDEX,USD,NaN,NaN,...,NaN,NaN,NaN,22,11,72.5,GREED,58.6,UPPER_HALF,31.4
448,^TWII,INDICES,TSEC CAPITALIZATION WEIGHTED ST,TWSE Capitalization Weighted Stock Index,^TWII,TAI,INDEX,TWD,NaN,NaN,...,NaN,NaN,NaN,3,4,67.4,GREED,83.5,NEAR_HIGH,32.4
449,^TYX,INDICES,Treasury Yield 30 Years,Treasury Yield 30 Years,^TYX,CGI,INDEX,USD,NaN,NaN,...,NaN,NaN,NaN,21,12,73.1,GREED,81.7,NEAR_HIGH,31.2
450,^VIX,INDICES,CBOE Volatility Index,CBOE Volatility Index,^VIX,CXI,INDEX,USD,NaN,NaN,...,NaN,NaN,NaN,20,1,25.3,FEAR,22.4,NEAR_LOW,33.5

In [9]:
import matplotlib as plt

In [7]:
df.corr(numeric_only=True)

,currentPrice,previousClose,open,dayLow,dayHigh,fiftyTwoWeekLow,fiftyTwoWeekHigh,fiftyDayAverage,twoHundredDayAverage,volume,...,pct_of_52w_high,analyst_upside_pct,market_cap_usd,sector_return_rank,sector_momentum_rank,asset_class_return_rank,asset_class_momentum_rank,fear_greed_proxy,week52_position_pct,composite_score
currentPrice,1.000000,0.999972,0.999997,0.999999,0.999998,0.827968,0.998947,0.999099,0.981558,0.155239,...,0.021254,0.035038,0.042657,-0.086688,-0.087943,-0.116228,-0.116041,-0.091209,0.059330,0.078617
previousClose,0.999972,1.000000,0.999925,0.999917,0.999911,0.799020,0.997737,0.999228,0.978653,0.060229,...,0.032909,0.035244,0.058113,-0.086644,-0.087909,-0.102830,-0.101312,-0.041270,0.049979,0.073512
open,0.999997,0.999925,1.000000,0.999997,0.999983,0.798846,0.997633,0.999092,0.978342,0.060173,...,0.032423,0.035122,0.058602,-0.086746,-0.088045,-0.102794,-0.101367,-0.042042,0.049405,0.073766
dayLow,0.999999,0.999917,0.999997,1.000000,0.999975,0.798889,0.997520,0.999008,0.978232,0.060574,...,0.032543,0.035065,0.058791,-0.086759,-0.088042,-0.103016,-0.101586,-0.041872,0.049593,0.073897
dayHigh,0.999998,0.999911,0.999983,0.999975,1.000000,0.795577,0.997676,0.999047,0.977398,0.059549,...,0.032040,0.035038,0.058417,-0.086585,-0.087814,-0.102340,-0.100929,-0.042549,0.049177,0.073687
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
asset_class_return_rank,-0.116228,-0.102830,-0.102794,-0.103016,-0.102340,-0.105811,-0.097431,-0.099526,-0.103918,-0.072482,...,-0.194440,0.068781,-0.083869,0.638826,0.447129,1.000000,0.718860,-0.143017,-0.420342,-0.219395
asset_class_momentum_rank,-0.116041,-0.101312,-0.101367,-0.101586,-0.100929,-0.103589,-0.096311,-0.098006,-0.101928,-0.067570,...,-0.253071,0.266252,0.127421,0.480266,0.550967,0.718860,1.000000,-0.228216,-0.413058,-0.406644
fear_greed_proxy,-0.091209,-0.041270,-0.042042,-0.041872,-0.042549,0.000688,-0.048187,-0.043142,-0.034309,-0.039824,...,0.849193,-0.599785,0.149000,-0.357124,-0.512982,-0.143017,-0.228216,1.000000,0.626498,0.725137
week52_position_pct,0.059330,0.049979,0.049405,0.049593,0.049177,0.031631,0.041549,0.046671,0.040677,-0.069931,...,0.786867,-0.487631,0.163439,-0.620662,-0.671786,-0.420342,-0.413058,0.626498,1.000000,0.651841
composite_score,0.078617,0.073512,0.073766,0.073897,0.073687,0.046157,0.068104,0.070930,0.063019,-0.052423,...,0.763114,-0.576346,0.118181,-0.491627,-0.643779,-0.219395,-0.406644,0.725137,0.651841,1.000000

In [ ]:
plt.scatter(df['currentPrice'],df['volume'])

AttributeError: module 'matplotlib' has no attribute 'scatter'

In [11]:
plt.plot('currentPrice')

AttributeError: module 'matplotlib' has no attribute 'plot'

In [6]:
bar=df.groupby('sector')['asset_class_momentum_rank'].mean()

In [ ]:
plt.bar(bar.index,bar.values)
plt.xticks(rotation=90)
plt.show()

AttributeError: module 'matplotlib' has no attribute 'bar'