In [1]:
print("python")

python

In [2]:
import pandas

In [ ]:
#Series,DataFrame

'''
syntax to create series
pandas.Series([1,2,3,4,5])
'''

'\nsyntax to create series\npandas.Series([1,2,3,4,5])\n'

In [4]:
pandas.Series([1,2,3,4,5,'Hello'])

0        1
1        2
2        3
3        4
4        5
5    Hello
dtype: object

In [5]:
pandas.Series([1,2,3,4,5])

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [6]:
data=[[1,2,3],[2,3,4],[3,4,5]]
column_names=['Age','Exp','Sal']

In [7]:
pandas.DataFrame(data,columns=column_names)

   Age  Exp  Sal
0    1    2    3
1    2    3    4
2    3    4    5

In [8]:
data=[[1,2,3],[2,3,4,6],[3,4,5]]
column_names=['Name','Age','Exp','Sal']

In [9]:
pandas.DataFrame(data,columns=column_names)

   Name  Age  Exp  Sal
0     1    2    3  NaN
1     2    3    4  6.0
2     3    4    5  NaN

In [8]:
d={'Age':[26,25,24,27],
   'Sal':[50000,35000,20000,51000]
   }

pandas.DataFrame(d)

NameError: name 'pandas' is not defined

In [ ]:
d={'Age':[26,25,27]
   'Sal':[35000,250000]
   }

In [9]:
import pandas

In [10]:
d={'Age':[26,25,24,27],
   'Sal':[50000,35000,20000,51000]
   }

pandas.DataFrame(d)

   Age    Sal
0   26  50000
1   25  35000
2   24  20000
3   27  51000

In [11]:
d={'Age':[26,25,27],
   'Sal':[50000,35000]
   }

pandas.DataFrame(d)

ValueError: All arrays must be of the same length